export class CollegeListEnum {
    orgName: string = '';
    orgType: string = '';
    name: string = '';
    codes: string = '';
    title: string = '';
    country: string = '';
    address: string = '';
    fafsaId: string = '';
    city: string = '';
    states: string = '';
    zipcode: string = '';
    fiscalYear: string = '';
    phone1: string = '';
    phone2: string = '';
    phone3: string = '';
    fax: string = '';
    website: string = '';
    email: string = '';
    notes: string = '';
    ncesId: any = null;
    inPullDown: boolean = false;
}